/*
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.dpdp.accelerator.consent.extensions.service.constants;

public final class ConsentHistoryServiceConstants {

    /**
     * {@code actionBy} recorded for a status-audit/history row generated by the consent expiry
     * job or lazy reconciliation, rather than a real user action.
     */
    public static final String SYSTEM_ACTOR_EXPIRY = "SYSTEM";

    private ConsentHistoryServiceConstants() {

    }

    /**
     * What triggered a status-audit/history row. AUTHORIZE is split into APPROVE/REJECT/REVOKE by
     * the actual per-authorizer decision, rather than one generic value that reads ambiguously
     * regardless of outcome.
     */
    public enum ActionType {
        CREATE,
        UPDATE,
        REVOKE,
        AUTHORIZE_APPROVE,
        AUTHORIZE_REJECT,
        AUTHORIZE_REVOKE,
        DELETE,
        EXPIRE
    }
}
